googleapis/artman

- CONTRIBUTING.rst
- README.rst
- USAGE.rst
- Move usage instructions to USAGE.rst
- Fix some incorrect references
- In USAGE.rst, add a warning that the library is in development and can
only be used by the development team at the moment
> Update the README for use in public

- USAGE.rst
Related to https://github.com/googleapis/googleapis/pull/22.
If this PR happens, USAGE should be updated like this.
> Update USAGE for trimming API name prefix

- pipeline/pipelines/code_generation_pipeline.py
- test/testdata/python_grpc_client_pipeline.baseline
If output directory is not clean (contains existing files),
packman generates a wrong setup.py and generating whl fails.
The misbehavior of packman is actually due to the side products
of this task, so simply removing task would solve the problem.
Ideally packman should be fixed to ignore unrelated files for
setup.py.
> Stop building whl file for grpc-python

- tox.ini
This is causing a build failure currently. We should figure out how
to enable it later. Per @michaelbausor, we probably never were
actually linting it; it was being ignored until a pylint update caused
it to become an error.
> Stop pylint'ing the test directory

- pipeline/pipelines/gapic_generation_pipeline.py
- pipeline/pipelines/grpc_generation_pipeline.py
- pipeline/tasks/gapic_tasks.py
- pipeline/tasks/package_tasks.py
- pipeline/tasks/protoc_tasks.py
- pipeline/tasks/publish_tasks.py
- test/testdata/java_core_proto_pub_pipeline.baseline
- test/testdata/java_grpc_client_pub_pipeline.baseline
- test/testdata/python_grpc_client_pub_pipeline.baseline
devpi upload failed during manual test by Jacob because the --from-dir
flag for "devpi upload" requires archive files
(see http://doc.devpi.net/latest/userman/devpi_commands.html#upload).
Had subprocess change into ouptut directory before running "devpi
upload".
Also deleted the GrpcPackageDirTask and GapicPackageDirTask
from package_tasks: now package_dir is set by GrpcPackmanTask or
GapicPackmanTask with the default_provides keyword. Maven and PyPI
upload is now done from package_dir rather than final_repo_dir.
Also made a trailing slash for repo_url optional.
> Fix bugs in Python GRPC/Gapic package publishing

- setup.py
pip install command looks up the requirements listed here.
Thus sometimes it will fail to install some dependencies when
the user installs artman through pip-install command.
> Add requirements into seteup.py

- execute_pipeline.py
This allows artman to process incomplete configs as in
https://github.com/googleapis/googleapis/pull/104
> Don't assume string exists during macro expansion

- execute_pipeline.py
Previously download was only triggered by a certain task name which
no longer exists.
Fixes #89
> Fix download condition

- pipeline/tasks/io_tasks.py
- test/test_io_tasks.py
Previously, a confusing error occurred remotely if the local_repo was
too big. Instead, validate the size locally and raise a meaningful
exception.
Fixes #74
> Improve error reporting for bad local_repo

- Dockerfile
This means we don't need to re-release packman and update the
Dockerfile every time we roll out an updated configuration of the
artman remote.
Note that eventually when artman is versioned we'll want to switch
back to pegging packman.
> Switch to installing packman from source

- pipeline/tasks/gapic_tasks.py
Formerly, packman was skipped for all Ruby/NodeJS Cloud GAPIC packages.
Actually, some packages require packman; the correct condtion is that
packman should be skipped if there is a handwritten layer on top of
GAPIC. This should be configured per-API instead of hard-coded into
artman.
Fixes #95
> Pass skip_packman as a pipeline_arg

- pipeline/utils/config_util.py
- test/test_pipeline_baseline.py
- test/testdata/googleapis_test/gapic/api/artman_library.yaml
- test/testdata/googleapis_test/gapic/lang/common.yaml
- THISDIR is no longer used in the real googleapis
- THISDIR causes problems when running in remote mode
- [geigerj/artman wrapper branch](https://github.com/geigerj/artman/tree/wrapper) relies on this change, but it's not directly related to the wrapper, so it seems good to separate it into its own PR.
Fixes #93
> Remove THISDIR macro expansion

- pipeline/pipelines/grpc_generation_pipeline.py
- pipeline/tasks/protoc_tasks.py
- test/testdata/csharp_grpc_client_pipeline.baseline
- test/testdata/ruby_grpc_client_pipeline.baseline
It was accidentally removed in #115.
Note that this change removes an flag that set the protoc gRPC plugin
to an empty value for Ruby and C#; presumably removing the empty flag
will have no effect.
FYI @swcloud @chrisdunelm regarding the modification to the Ruby/C# gRPC codegen command; see the baseline file change for details.
> Turn gRPC codegen back on for Python

- pipeline/tasks/protoc_tasks.py
#116 actually removed the flag name from the grpc plugin param. ~~I didn't notice this because no language is currently passing a grpc plugin to protoc directly.~~
EDIT: this fixes a breakage in the Ruby gRPC pipeline. #119 filed for why the baseline tests don't reflect that.
> Fix typo in plugin param

- pipeline/tasks/protoc_tasks.py
- test/testdata/ruby_grpc_client_pipeline.baseline
Ruby gRPC plugin is not used with the Ruby protoc package.
> Remove Ruby gRPC plugin

- pipeline/tasks/python_grpc_tasks.py
Context is the same as with https://github.com/googleapis/googleapis/pull/209; this is needed to prevent Python codegen from changing the package to `google.cloud.grpc.iam.[...]`.
> Treat google.iam as common proto package

- pipeline/tasks/package_metadata_tasks.py
A user running remote artman encountered a failure where artman dumped
a `!!python/unicode 'v1beta1'` object in the package metadata. This
caused an error when the `toolkit` Java code tried to load the yaml file.
Use `safe_dump` instead of `dump` to ensure that Python objects are
not being dumped in the package metadata.
> Don't dump Python classes in package metadata YAML

- Dockerfile
- k8s/README.rst
- k8s/dev/dev.yaml
- k8s/prod/prod.yaml
Start the artman conductor as part of the deployment file instead of Dockerfile.
> Inroduce kubenetes deployment yamls for dev and prod environments. 

- Dockerfile
- artman-user-config-in-docker.yaml
Include a default artman user config in the docker image so that there will be no need to setup artman config in the docker image.
> Include a default artman user config in the docker image

- artman/tasks/package_metadata_tasks.py
This `proto_test_deps` field is currently used by the Java gapic build files to declare test dependencies.
> Support proto_test_deps in metadata config

- artman/cli/main.py
To my knowledge, we always want the dummy gRPC classes (at least
until we get a protoc plugin). Enable this by default.
> Enable doc generation for Ruby by default

- artman/pipelines/grpc_generation.py
It was effectively a no-op anyway, since no files generated in the
pipeline were used by the artman config.
> Turn NodeJS gRPC client pipeline into a no-op

- Dockerfile
bump toolkit commit in artman Docker image so that the generated GAPICs are compatible with the latest GAX
> bump toolkit commit in artman Docker image

- artman/config/converter.py
> Underscore separate multiword API names in Ruby output dir

- .circleci/config.yml
- artman/cli/main.py
Besides `pip install --upgrade` alone doesn't seem to reinstall artman without `-e`.
> Fix a bug that mishandles the path to artman config

- .circleci/config.yml
- artman/cli/main.py
- artman/tasks/publish/local.py
- requirements.txt
- test/cli/test_main.py
Introduce optional --local-repo-dir subflag to `publish --dry-run` command, which points to a local github repo directory, that will then be mounted to docker container. Then google-cloud-java team can easily write a 20-line python script (excluding constant string list pointing to different artman yaml) to do batch refresh. And any customization, if necessary, can be done in the repo-specific batch script without coupling with artman.
>  Introduce optional --local-repo-dir subflag to `publish --dry-run` command

- .circleci/config.yml
Running golden_test using googleapis/artman:latest image is not giving us good coverage as many golden changes are caused by toolkit/googleapis repo bump. Therefore, removing this top-level test. Note: `build_and_push_docker_image` CI workflow still includes this golden test. More importantly, that is where a new docker image is built and tested.
> Remove golden-test from the top-level tests

- requirements.txt
This is needed to generate ResourceName interface methods.
> Update protoc-gapic-plugin to 0.0.8

- artman/cli/main.py
- artman/config/converter.py
- artman/pipelines/core_generation.py
- artman/pipelines/gapic_generation.py
- artman/pipelines/grpc_generation.py
- artman/tasks/gapic_tasks.py
- artman/tasks/package_metadata_tasks.py
- artman/tasks/protoc_tasks.py
- artman/utils/protoc_utils.py
- test/cli/test_main.py
- test/config/test_converter.py
- test/config/testdata/expected_pubsub_java_legacy_config.yaml
- test/config/testdata/expected_pubsub_java_proto_legacy_config.yaml
- test/config/testdata/expected_pubsub_python_legacy_config.yaml
- test/tasks/test_gapic.py
- test/test_package_metadata_task.py
- Before: `gapic_yaml` & `service_yaml` were each added to a single-item list (as `gapic_api_yaml` & `service_yaml`)
- After: the original `gapic_yaml` & `service_yaml` values are plumbed through everywhere
This conversion to a list was done because we used to merge with the legacy language configs that have since been deprecated. 
Net deletion!
> Converting gapic_api_yaml/service_yaml to strings internally

- .circleci/config.yml
Fixing two bugs in #449 that prevented auto-release from working.
1. We use docker inside docker (which is kind of bad but we need to do it to build images inside CircleCI). The docker image that can run docker is very limited (e.g. no Python and no openssl). So we need to use docker to run everything other than docker!  (see the diff if my explanation is unclear)
2. We still want to run the whole testing before releasing, so running smoke tests not only for master branch, but also for tagged commits.
> fix auto-release

- artman/cli/main.py
- artman/tasks/gapic_tasks.py
- test/cli/test_main.py
- test/tasks/test_gapic.py
I have not been able to figure out how to make the parser accept everything after a "-- " as arguments. I can do it on a standalone example, but I think the generate subcommand does not interact well with it.
This PR includes tests.
This addresses #508. The immediate motivation is to enable easier sample gen for languages in which samples have not yet been officially launched.
> Add --generator_args to pass a string of args to gapic-generator

- Dockerfile
Bump gapic-generator hash to include:
* change Go gapics use gax-go/v2
* Samplegen: initialize a resource name with parameters
* [golang] Mark "beta" APIs as beta
> bump gapic-generator hash

- Dockerfile
The updated hash includes [googleapis/gapic-generator#2542](https://github.com/googleapis/gapic-generator/pull/2542) which fixed a Go example_test.go import churn problem.
It also includes changes for Bazel Go build rules and disco-gapic fixes.
> Update gapic-generator hash

- Dockerfile
- SampleGen: use the correct default calling form for Java LRO methods
- SampleGen: generate the correct Gemfile for Ruby samples
- SampleGen: Accept enum values as CLI flags
- SampleGen: use application plugin in build.gradle of the sample package
- Java: Remove duplicate imports in Java
- Python: avoid coverage failure when no `_shared_modules` are present
> Release 0.21.0

- artman/utils/protoc_utils.py
we are [failing to run synthtool each night](https://github.com/googleapis/nodejs-grafeas/issues/5) because `google` is the only supported top level folder for protos.
> fix: grafeas can also be a top-level protocol folder

- Dockerfile
The following changes in gapic-generator is included in this release:
- Bazel: Add GAPIC Bazel Extensions for PHP (#2821)
- Add GAPIC_CODE artifact type support for PHP (#2801)
- C#: Add ClientBuilder generation (#2796)
- SampleGen: Conform to Ruby style requirements (#2819)
- SampleGen: parse floats from CLI (#2820)
- SampleGen: Python template update: add unicode, remove six (#2811)
- SampleGen: Remove [START/END region_tag_core] region tags (#2810)
Note:
- For Java generation please continue to use artman 0.22.0.
> Release 0.24.0

- artman/cli/main.py
The temporary directory was overridden during `pipeline_args.update(config_args)`.
> Really use temporary directory when generating discogapic configs

- .circleci/config.yml
Let's move the samplegen smoke test to the regular smoke test task and save 10 minutes on rebuilding docker image.
Also, removing `-e` flag of `docker login` that stopped working.
> speedup CircleCI a little bit

- Dockerfile
Changes since the last update:
- googleapis/gapic-generator#2947 Update intersphinx reference for google.api_core
- googleapis/gapic-generator#2901 SampleGen: print a descriptive line in Java LRO samples
- googleapis/gapic-generator#2957 Support _virtual_imports in path of proto_library targets
- googleapis/gapic-generator#2888 node: make the generated Node.js libraries work with grpc-fallback and browser
Big changes in this release: Node.js libraries now load protos from JSON.
> release v0.36.0

- Dockerfile
Releasing version v0.36.1.
Includes a fix for Node.js: https://github.com/googleapis/gapic-generator/pull/2960
> release v0.36.1

- Dockerfile
To include the following features from gapic-generator:
- SampleGen: generates sample manifest file for Java samples (#2992)
- Python: Update URL for 'requests' Sphinx inventory. (#2990)
> Release 0.38.0

- Dockerfile
To include the following changes from gapic generator:
- Fix iam dependency resolution for java_gapic_assembly_gradle_pkg
- Parse resource name annotations from imported protos too
and the following changes in artman:
- Bug fix when resource names plugin is called without gapic.yaml
> Release 0.39.0

- Dockerfile
To include the following feature from gapic-generator:
- SampleGen: update Node.js const name for library package (#2969)
> Release 0.40.2

- Dockerfile
gapic-generator: No changes
artman:
* add grpc_service_config attribute to artman config (https://github.com/googleapis/artman/pull/755)
> release v0.41.0

- Dockerfile
- requirements.txt
It turns out we might need to update internal googleapis copy (inside the Docker image) since we updated `google/cloud/common_resources.proto`. I'm really unsure how exactly it is used, but we got a bug report that this file is missing, and this is the first place I thought of. Let's try updating this hash.
> update googleapis hash

- Dockerfile
The `googleapis` repository inside the Docker image has been updated in this release.
Also, `protoc` v3.10 is now used for Java (#770).
> release v0.42.2

- Dockerfile
New features:
- node.js: feat: add explicit require for mocha https://github.com/googleapis/gapic-generator/pull/3063
- python: un-deprecate resource name functions https://github.com/googleapis/gapic-generator/pull/3062
- python: deprecation warning for Python 2.7 https://github.com/googleapis/gapic-generator/pull/3059
- bazel-related fixes
> release v0.43.0

- Dockerfile
- requirements.txt
Include the following features:
gapic generator:
- Support empty method signatures (#3067)
- Stop guessing entity names for patterns of multi-pattern resources (#3044)
resource name plugin:
- Support the new multi-pattern resource name (#66)
> Update resource name plugin version and gapic generator hash

- .circleci/config.yml
- artman/tasks/protoc_tasks.py
- noxfile.py
- test/tasks/data/googleapis/google/go_package_example/v1/first.proto
- test/tasks/data/googleapis/google/go_package_example/v1/second.proto
- test/tasks/test_protoc.py
In this PR:
- make sure we pass all the protos to the same `protoc` invocation for all languages except Go. For Go, keep doing what we are doing: split list of protos into several invocation based on `go_package` option.
- added tests that cover this functionality.
- when adding those tests, figured out that the code being changed does not work on Python 2.7 at all. Since it's dead and we use 3.x inside Docker anyway, let's stop testing on 2.7.
- also, made sure our tests work with the latest `nox` version.
All in the same PR - sorry for that!
> run protoc in one invocation (and stop testing Python 2.7)

- Dockerfile
Features included:
- feat: set x-goog-user-project header for Ruby
- feat: adds reserved name support for PHP and reserved name tests (https://github.com/googleapis/gapic-generator/pull/3100)
- Update protoc-java-resource-name-plugin (#812)
> release 1.1.0

- Dockerfile
- requirements.txt
- test-requirements.txt
- test/golden/library_example.golden
gapic-generator:
- feat: add the last segment when generating names for singleton resoures
- fix: add null check and better error message when referenced resources are not found
- feat: Support extra plugin_args for php bazel rules rules (#3165)
- feat: support '*' in resource definition (#3163)
- fix: align text in license (#3158)
- fix(python): add PROJECT_ID for python-system-test (#3161)
- fix(PYTHON): update nox file and modernize to new interface (#3156)
resource name plugin
- feat: add the last segment when generating names for singleton resources
- feat: support * annotation in resource def (#84) 
- feat: trace up only one level when calculating parent types with singleton resources
- fix: stop generating `parseList` and `toStringList` if a multi-pattern resource class has …
> Update gapic-generator hash and Java resource name plugin
