googleapis/artman

- .gitmodules
- .travis.yml
- test-requirements.txt
- tox.ini
Pre-push hook installed.
Change-Id: I68128cd8b4b8536f6bf6c0a6c679a9ad5be449bf
> Add travis+codecov configuration

- pipeline/pipelines/code_generation_pipeline.py
- pipeline/tasks/gapic_tasks.py
- pipeline/tasks/packman_tasks.py
- pipeline/tasks/protoc_tasks.py
- test/testdata/python_gapic_client_pipeline.baseline
- test/testdata/ruby_gapic_client_pipeline.baseline
> Run packman for gapic result

- Dockerfile
- requirements.txt
- scripts/setup_node4.sh
Modify Dockerfile and requirements.txt to include more dependency installation in order to support running pipeline jobs remotely.
> Update Dockerfile and requirements.txt

- USAGE.rst
> Add Python, Ruby doc pipelines to USAGE

- Dockerfile
- pipeline/pipelines/grpc_generation_pipeline.py
- pipeline/tasks/protoc_tasks.py
- test/testdata/ruby_grpc_client_pipeline.baseline
> Added a task to RubyGrpcPipeline to copy files to final repo dir.

- Dockerfile
- pipeline/pipelines/grpc_generation_pipeline.py
- pipeline/tasks/protoc_tasks.py
- test/testdata/ruby_grpc_client_pipeline.baseline
> Made artman not depend on packman for ruby grpc generation.

- pipeline/tasks/package_metadata_tasks.py
- pipeline/tasks/protoc_tasks.py
- test/test_package_metadata_task.py
- test/testdata/google-cloud-fake-v1_package.yaml
- test/testdata/googleapis_test/gapic/api/artman_library.yaml
- test/testdata/googleapis_test/gapic/packaging/dependencies.yaml
See https://github.com/googleapis/toolkit/pull/984 for context.
To be merged simultaneously with https://github.com/googleapis/toolkit/pull/984, https://github.com/googleapis/googleapis/pull/248
> Include proto_gen_pkg_deps in package metadata

- .circleci/config.yml
- test/smoketest_artman.py
The artman yamls in the whitelist were either fixed or removed.
> Keep an empty WHITEST in artman smoketest

- artman/cli/main.py
- test/golden/library_example_gapic.yaml
- test/tasks/data/googleapis/google/pubsub/v1/pubsub_gapic.yaml
Previous image incompatible with `config_schema_version` in GAPIC yaml
> Update docker image

- artman/cli/main.py
Previously, when toolkit generation failed, owner permission of any intermediate files will not be changed. Therefore, these files are granted with the user permission inside the docker container instead of the host user permission.
> Always change owner permission of the output files 

- artman/tasks/python_grpc_tasks.py
- test/tasks/test_python_grpc.py
This reverts commit dcff409a2b4872f564d349cf1b292c452c08cd0e.
> Reverts googleapis/artman#332

- Dockerfile
Includes some Ruby toolkit fixes
> Bump toolkit/googleapis commits

- Dockerfile
- setup.py
The artman user config schema has been changed.
> Bump artman to 0.7.0

- Dockerfile
- setup.py
Updating version and commit hashes to the latest master commits.
Note: before this is released, I will make one (or more) PRs that will change `.circleci/config.yml` to make it easier to make artman releases.
> release 0.12.1: updating googleapis and toolkit

- artman/pipelines/gapic_generation.py
Fixes https://github.com/googleapis/artman/issues/479
> Fixing GAPIC_ONLY

- Dockerfile
gapic generator fix: https://github.com/googleapis/gapic-generator/pull/2421
> Bump gapic-generator version to pick up fix

- artman/tasks/python_grpc_tasks.py
- test/tasks/test_python_grpc.py
> Resolve failure when generating python gapics for iamcredentials

- .gitignore
- Dockerfile
And gitignore the /bin folder.
> Update gapic-generator hash

- CONTRIBUTING.rst
Fixes #585 
Updated `CONTRIBUTING.rst` to remove typos in `Include tests` section.
> Fixed typos in CONTRIBUTING.rst

- Dockerfile
Also waiting for https://circleci.com/gh/googleapis/artman/9555 to pass.
> Release v0.16.20

- Dockerfile
Release a new Artman with protoc 3.7.1.
> Release 0.16.21

- Dockerfile
> Release v0.23.0

- .circleci/config.yml
- Dockerfile
> Add SampleGen smoke tests to CircleCI

- .circleci/config.yml
- Dockerfile
- test/smoketest_artman.py
upd. (@alexander-fenster) also upgraded some stuff inside :)
> whitelist osconfig/agenendpoint PHP

- Dockerfile
Include features from the previous PR.
> Release 0.42.0

- install_protoc.sh
> use protoc v3.10.0 for Java

- install_protoc.sh
I just hope it does not break anything in client libraries :)
> use latest protoc version

- Dockerfile
Release a patch because the new version contains only bug fix.
> Release 0.44.1

- Dockerfile
> Release 2.0.0
